/** @ignore */
export const coutries: any[] = [
    {
        'id': 233,
        'countryCode': 'US',
        'countryName': 'United States',
        'currencyCode': 'USD',
        'isoNumeric': '840',
        'capital': 'Washington',
        'continentName': 'North America',
        'continent': 'NA',
        'languages': 'en-US,es-US,haw,fr',
        'isoAlpha3': 'USA',
        'geonameId': 6252001,
        'phonecode': '1',
        'currency_symbol': '&#36;',
        'currency_name': 'United States Dollar'
    },
    {
        'id': 105,
        'countryCode': 'IN',
        'countryName': 'India',
        'currencyCode': 'INR',
        'isoNumeric': '356',
        'capital': 'New Delhi',
        'continentName': 'Asia',
        'continent': 'AS',
        'languages': 'en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc',
        'isoAlpha3': 'IND',
        'geonameId': 1269750,
        'phonecode': '91',
        'currency_symbol': '&#8377;',
        'currency_name': 'Indian Rupee'
    },
    {
        'id': 198,
        'countryCode': 'SG',
        'countryName': 'Singapore',
        'currencyCode': 'SGD',
        'isoNumeric': '702',
        'capital': 'Singapore',
        'continentName': 'Asia',
        'continent': 'AS',
        'languages': 'cmn,en-SG,ms-SG,ta-SG,zh-SG',
        'isoAlpha3': 'SGP',
        'geonameId': 1880251,
        'phonecode': '65',
        'currency_symbol': '&#83;&#36;',
        'currency_name': 'Singapore Dollar'
    },
    {
        'id': 95,
        'countryCode': 'HK',
        'countryName': 'Hong Kong',
        'currencyCode': 'HKD',
        'isoNumeric': '344',
        'capital': 'Hong Kong',
        'continentName': 'Asia',
        'continent': 'AS',
        'languages': 'zh-HK,yue,zh,en',
        'isoAlpha3': 'HKG',
        'geonameId': 1819730,
        'phonecode': '852',
        'currency_symbol': '&#72;&#75;&#36;',
        'currency_name': 'Hong Kong Dollar'
    },
    {
        'id': 13,
        'countryCode': 'AU',
        'countryName': 'Australia',
        'currencyCode': 'AUD',
        'isoNumeric': '036',
        'capital': 'Canberra',
        'continentName': 'Oceania',
        'continent': 'OC',
        'languages': 'en-AU',
        'isoAlpha3': 'AUS',
        'geonameId': 2077456,
        'phonecode': '61',
        'currency_symbol': '&#65;&#36;',
        'currency_name': 'Australian Dollar'
    },
    {
        'id': 20,
        'countryCode': 'BE',
        'countryName': 'Belgium',
        'currencyCode': 'EUR',
        'isoNumeric': '056',
        'capital': 'Brussels',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'nl-BE,fr-BE,de-BE',
        'isoAlpha3': 'BEL',
        'geonameId': 2802361,
        'phonecode': '32',
        'currency_symbol': '&#8364;',
        'currency_name': 'Euro'
    },
    {
        'id': 38,
        'countryCode': 'CA',
        'countryName': 'Canada',
        'currencyCode': 'CAD',
        'isoNumeric': '124',
        'capital': 'Ottawa',
        'continentName': 'North America',
        'continent': 'NA',
        'languages': 'en-CA,fr-CA,iu',
        'isoAlpha3': 'CAN',
        'geonameId': 6251999,
        'phonecode': '1',
        'currency_symbol': '&#67;&#97;&#110;&#36;',
        'currency_name': 'Canadian Dollar'
    },
    {
        'id': 57,
        'countryCode': 'DE',
        'countryName': 'Germany',
        'currencyCode': 'EUR',
        'isoNumeric': '276',
        'capital': 'Berlin',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'de',
        'isoAlpha3': 'DEU',
        'geonameId': 2921044,
        'phonecode': '49',
        'currency_symbol': '&#8364;',
        'currency_name': 'Euro'
    },
    {
        'id': 111,
        'countryCode': 'JE',
        'countryName': 'Jersey',
        'currencyCode': 'GBP',
        'isoNumeric': '832',
        'capital': 'Saint Helier',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'en,pt',
        'isoAlpha3': 'JEY',
        'geonameId': 3042142,
        'phonecode': '44',
        'currency_symbol': '&#163;',
        'currency_name': 'British Pound Sterling'
    },
    {
        'id': 134,
        'countryCode': 'LU',
        'countryName': 'Luxembourg',
        'currencyCode': 'EUR',
        'isoNumeric': '442',
        'capital': 'Luxembourg',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'lb,de-LU,fr-LU',
        'isoAlpha3': 'LUX',
        'geonameId': 2960313,
        'phonecode': '352',
        'currency_symbol': '&#8364;',
        'currency_name': 'Euro'
    },
    {
        'id': 158,
        'countryCode': 'MY',
        'countryName': 'Malaysia',
        'currencyCode': 'MYR',
        'isoNumeric': '458',
        'capital': 'Kuala Lumpur',
        'continentName': 'Asia',
        'continent': 'AS',
        'languages': 'ms-MY,en,zh,ta,te,ml,pa,th',
        'isoAlpha3': 'MYS',
        'geonameId': 1733045,
        'phonecode': '60',
        'currency_symbol': '&#82;&#77;',
        'currency_name': 'Malaysian Ringgit'
    },
    {
        'id': 43,
        'countryCode': 'CH',
        'countryName': 'Switzerland',
        'currencyCode': 'CHF',
        'isoNumeric': '756',
        'capital': 'Berne',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'de-CH,fr-CH,it-CH,rm',
        'isoAlpha3': 'CHE',
        'geonameId': 2658434,
        'phonecode': '41',
        'currency_symbol': '&#67;&#72;&#70;',
        'currency_name': 'Swiss Franc'
    },
    {
        'id': 2,
        'countryCode': 'AE',
        'countryName': 'United Arab Emirates',
        'currencyCode': 'AED',
        'isoNumeric': '784',
        'capital': 'Abu Dhabi',
        'continentName': 'Asia',
        'continent': 'AS',
        'languages': 'ar-AE,fa,en,hi,ur',
        'isoAlpha3': 'ARE',
        'geonameId': 290557,
        'phonecode': '971',
        'currency_symbol': '&#1583;.&#1573;',
        'currency_name': 'United Arab Emirates Dirham'
    },
    {
        'id': 77,
        'countryCode': 'GB',
        'countryName': 'United Kingdom of Great Britain and Northern ',
        'currencyCode': 'GBP',
        'isoNumeric': '826',
        'capital': 'London',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'en-GB,cy-GB,gd',
        'isoAlpha3': 'GBR',
        'geonameId': 2635167,
        'phonecode': '44',
        'currency_symbol': '&#163;',
        'currency_name': 'British Pound Sterling'
    },
    {
        'id': 1,
        'countryCode': 'AD',
        'countryName': 'Andorra',
        'currencyCode': 'EUR',
        'fipsCode': 'AN',
        'isoNumeric': '020',
        'north': '42.65604389629997',
        'south': '42.42849259876837',
        'east': '1.7865427778319827',
        'west': '1.4071867141112762',
        'capital': 'Andorra la Vella',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'ca',
        'isoAlpha3': 'AND',
        'geonameId': 3041565,
        'status': true,
        'phonecode': '376',
        'currency_symbol': '&#8364;',
        'currency_name': 'Euro'
    },
    {
        'id': 11,
        'countryCode': 'AS',
        'countryName': 'American Samoa',
        'currencyCode': 'USD',
        'fipsCode': 'AQ',
        'isoNumeric': '016',
        'north': '-11.0497',
        'south': '-14.382478',
        'east': '-169.416077',
        'west': '-171.091888',
        'capital': 'Pago Pago',
        'continentName': 'Oceania',
        'continent': 'OC',
        'languages': 'en-AS,sm,to',
        'isoAlpha3': 'ASM',
        'geonameId': 5880801,
        'status': true,
        'phonecode': '1684',
        'currency_symbol': '&#36;',
        'currency_name': 'United States Dollar'
    },
    {
        'id': 81,
        'countryCode': 'GG',
        'countryName': 'Guernsey',
        'currencyCode': 'GBP',
        'fipsCode': 'GK',
        'isoNumeric': '831',
        'north': '49.731727816705416',
        'south': '49.40764156876899',
        'east': '-2.1577152112246267',
        'west': '-2.673194593476069',
        'capital': 'St Peter Port',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'en,fr',
        'isoAlpha3': 'GGY',
        'geonameId': 3042362,
        'status': true,
        'phonecode': '44',
        'currency_symbol': '&#163;',
        'currency_name': 'British Pound Sterling'
    },
    {
        'id': 129,
        'countryCode': 'LI',
        'countryName': 'Liechtenstein',
        'currencyCode': 'CHF',
        'fipsCode': 'LS',
        'isoNumeric': '438',
        'north': '47.2706251386959',
        'south': '47.0484284123471',
        'east': '9.63564281136796',
        'west': '9.47167359782014',
        'capital': 'Vaduz',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'de-LI',
        'isoAlpha3': 'LIE',
        'geonameId': 3042058,
        'status': true,
        'phonecode': '423',
        'currency_symbol': '&#67;&#72;&#70;',
        'currency_name': 'Swiss Franc'
    },
    {
        'id': 191,
        'countryCode': 'RU',
        'countryName': 'Russia',
        'currencyCode': 'RUB',
        'fipsCode': 'RS',
        'isoNumeric': '643',
        'north': '81.857361',
        'south': '41.188862',
        'east': '-169.05',
        'west': '19.25',
        'capital': 'Moscow',
        'continentName': 'Europe',
        'continent': 'EU',
        'languages': 'ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog',
        'isoAlpha3': 'RUS',
        'geonameId': 2017370,
        'status': true,
        'phonecode': '7',
        'currency_symbol': '&#1088;&#1091;&#1073;',
        'currency_name': 'Russian Ruble'
    },
];
